### ISSUE TITLE
Error in solve.default(Ddp.cp) : 

### ISSUE THREAD

**Issue by ChingyCheng** [rachaelpung/serial_interval_covid_b.1.617.2#1]
**Error in solve.default(Ddp.cp) : 
system is computationally singular: reciprocal condition number = 2.24196e-33**
There is a problem i can't solve, can you help me ,the code isn't run ,i tyr many methods but i can't know how to solve it. Thanks for your help1

7.solve.default(Ddp.cp)
6.solve(Ddp.cp)
5.sn.infoUv(dp = fit$dp, x = x, y = yInfo, w = w, penalty = penalty)
4.selm.fit(x, y, family = family, start, w = w, fixed.param = fixed.param, 
  offset = offset, selm.control = contr)
3.selm(x ~ 1)
2.FUN(X[[i]], ...)
1.lapply(1:1000, function(i) {
   x = sampleSerialInt[ITER == i, SERIAL_INTERVAL_PRE_LD]
   skew_mod = selm(x ~ 1)
    fit = dsn(-3:15, dp = skew_mod@param$dp) ...

**Comment by rachaelpung** [comment]
Hi ChingyCheng, you might want to try setting a lower number of iterations and see if it works? The small sample size can result in a sampled distribution that does not fit a skew logistic distribution under certain seed values and hence the error.

**Comment by ChingyCheng** [comment]
I try it and it running successfully, I'm currently trying to do something related to the epidemic by myself. Can I ask you if I have any questions? If it's convenient for you, I would like to add your contact information. 
Thank you for your reply.

Your sincerely 
Chingy Cheng

**Comment by rachaelpung** [comment]
sure, my working email is rachael.pung@lshtm.ac.uk
